name: Production - Optimize & Deploy
on:
  push:
    branches: [main]

jobs:
  optimize-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: |
          npm init -y
          npm install --save-dev clean-css-cli html-minifier-terser
          
      - name: Minify CSS
        run: |
          npx cleancss -o styles.min.css styles.css
          
      - name: Minify HTML
        run: |
          npx html-minifier-terser --collapse-whitespace --remove-comments --minify-css --minify-js -o index.min.html index.html
          npx html-minifier-terser --collapse-whitespace --remove-comments --minify-css --minify-js -o 404.min.html 404.html
          
      - name: Update HTML references
        run: |
          sed -i 's/styles\.css/styles.min.css/g' index.min.html
          sed -i 's/styles\.css/styles.min.css/g' 404.min.html
          
      - name: Prepare production files
        run: |
          mv index.min.html index.html
          mv 404.min.html 404.html
          mv styles.min.css styles.css
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          cname: erik-dev.com
