name: Staging - Build & Deploy
on:
  push:
    branches: [staging]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Validate HTML & CSS
        run: |
          npx html-validate index.html 404.html
          npx stylelint styles.css
          
      - name: Test site locally
        run: |
          npx serve -s . &
          sleep 5
          curl -f http://localhost:3000 || exit 1
          
      - name: Deploy to GitHub Pages (staging)
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/staging'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          destination_dir: staging
